name: Android Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Before
        run: chmod +x gradlew
      - name: Run Test
        run: ./gradlew test
        
      - name: Build Project
        run: ./gradlew assemble
      
      - name: SpotBugs
        run: ./gradlew spotbugsDebug
        
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: asdasd
          alias: asdasd
          keyStorePassword: asdasd
          keyPassword: asdasd
          
      - uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: app/build/outputs/apk/release

