name: Android Build

on: push

jobs:
  generate-javadoc:

    runs-on: ubuntu-latest

    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Javadoc
        run: javadoc -package -sourcepath /app/src/main/java/com/app/advancedtodolist -subpackages java -exclude java.net:java.lang
